/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define IPTSD_CONFIG_DIR "/etc/iptsd.d"

#define IPTSD_CONFIG_FILE "/etc/iptsd.conf"

#define IPTSD_FORCE_ACCESS_CHECKS 0

#define IPTSD_PRESET_DIR "/usr/local/share/iptsd"

